services:
  - type: web
    name: discord-report-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: MOD_ROLE_ID
        sync: false
      - key: ADMIN_ROLE_ID
        sync: false
      - key: SCOOTER_ID
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: MOD_CHANNEL_ID
        sync: false
